module.exports = {
  env: {
    CHAIN_ID: process.env.CHAIN_ID,
    POLIS_APP_ID: process.env.POLIS_APP_ID,
    POLIS_REDIRECT_URL: process.env.POLIS_REDIRECT_URL,
    STARLEDGER_ACCOUNT_ADDRESS: process.env.STARLEDGER_ACCOUNT_ADDRESS,
    STARLEDGER_API_URL: process.env.STARLEDGER_API_URL,
    STARLEDGER_CDN_URL: process.env.STARLEDGER_CDN_URL,
    STARLEDGER_CONTRACT_ADDRESS: process.env.STARLEDGER_CONTRACT_ADDRESS,
    STARLEDGER_MINT_CONTRACT_ADDRESS:
      process.env.STARLEDGER_MINT_CONTRACT_ADDRESS,
    STARLEDGER_NFT_CONTRACT_ADDRESS:
      process.env.STARLEDGER_NFT_CONTRACT_ADDRESS,
  },
};
